runtime: nodejs18
instance_class: F1

env_variables:
  NODE_ENV: production

handlers:
  # Serve static files from build/ directory
  - url: /static
    static_dir: build/static

  - url: /(.*\.(ico|json|png|jpg|svg|js|css))
    static_files: build/\1
    upload: build/.*\.(ico|json|png|jpg|svg|js|css)

  # Redirect all other URLs to index.html (for SPA routing)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
