steps:
  - name: 'node:21'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node:21'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
